# Set the prefix key to Ctrl-a (if you prefer it over Ctrl-b)
# set -g prefix C-a

# Create a new session named "failmode" and set it as the default session
new-session -d -s failmode

# Create Window 1 with a single pane
new-window -n "failmode" -t failmode:1
send-keys -t 0 "awslogin failmode" C-m

# Create Window 1 with two panes
new-window -n "bash-my-aws" -t failmode:2

# Split the first pane horizontally
split-window -v

# Send commands to the panes (e.g., navigate to a directory)
send-keys -t 0 "awslogin bash-my-aws" C-m
send-keys -t 1 "awslogin-firefox bash-my-aws" C-m

# Attach to the session
attach-session -t failmode

